import pandas as pd
import wget

# Download datasets
url = 'https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/owid-covid-data.csv'
wget.download(url)

dataset = pd.read_csv('owid-covid-data.csv')
dataset = dataset.drop('iso_code', axis=1)
dataset = dataset.drop('continent', axis=1)
dataset = dataset.drop('new_cases_smoothed', axis=1)
dataset = dataset.drop('new_deaths_smoothed', axis=1)
dataset = dataset.drop('new_cases_smoothed_per_million', axis=1)
dataset = dataset.drop('total_deaths_per_million', axis=1)
dataset = dataset.drop('new_deaths_per_million', axis=1)
dataset = dataset.drop('new_deaths_smoothed_per_million', axis=1)
dataset = dataset.drop('icu_patients_per_million', axis=1)
dataset = dataset.drop('hosp_patients_per_million', axis=1)
dataset = dataset.drop('weekly_icu_admissions_per_million', axis=1)
dataset = dataset.drop('weekly_hosp_admissions_per_million', axis=1)
dataset = dataset.drop('total_tests_per_thousand', axis=1)
dataset = dataset.drop('new_tests_per_thousand', axis=1)
dataset = dataset.drop('new_tests_smoothed', axis=1)
dataset = dataset.drop('new_tests_smoothed_per_thousand', axis=1)
dataset = dataset.drop('tests_per_case', axis=1)
dataset = dataset.drop('tests_units', axis=1)
dataset = dataset.drop('people_fully_vaccinated', axis=1)
dataset = dataset.drop('new_vaccinations_smoothed', axis=1)
dataset = dataset.drop('total_vaccinations_per_hundred', axis=1)
dataset = dataset.drop('people_vaccinated_per_hundred', axis=1)
dataset = dataset.drop('people_fully_vaccinated_per_hundred', axis=1)
dataset = dataset.drop('new_vaccinations_smoothed_per_million', axis=1)
dataset = dataset.drop('population_density', axis=1)
dataset = dataset.drop('median_age', axis=1)
dataset = dataset.drop('aged_65_older', axis=1)
dataset = dataset.drop('aged_70_older', axis=1)
dataset = dataset.drop('extreme_poverty', axis=1)
dataset = dataset.drop('cardiovasc_death_rate', axis=1)
dataset = dataset.drop('diabetes_prevalence', axis=1)
dataset = dataset.drop('female_smokers', axis=1)
dataset = dataset.drop('male_smokers', axis=1)
dataset = dataset.drop('handwashing_facilities', axis=1)
dataset = dataset.drop('hospital_beds_per_thousand', axis=1)
dataset = dataset.drop('life_expectancy', axis=1)
dataset = dataset.drop('human_development_index', axis=1)
dataset = dataset.drop('excess_mortality', axis=1)
print(dataset)